### ISSUE TITLE
Wrong coordinates in rmob exported data

### ISSUE THREAD

**Issue by kaklik** [bolidozor/rmob-export#19]
Some stations have error message "Error in Latitude minute value = 74 input in your Rmob Field Area" at theirs [rmob.org](http://www.rmob.org/livedata/main.php) page. 

The problem is a wrong coordinates format in rmob exported data. e.g. http://www.rmob.org/livedata/live_datas/HFN-R1_082017rmob.TXT

Where

[Observer]HFN-R1
[Country]Czech Republic
[City]Jindrichuv Hradec
[Longitude]015d03 E
[Latitude]049d748 N
[Longitude GMAP]015.001
[Latitude GMAP]049.130
[Frequencies]143 050 000 Hz
[Antenna]1/4 GP
[Azimut Antenna] 0
[Elevation Antenna] 0
[Pre-Amplifier]LNA01A www.mlab.cz
[Receiver]RMDS02E www.mlab.cz
[Observing Method]Fordward scattering
[Remarks]ODROID-C2

There are 
[Longitude]015d03 E  
[Latitude]049d748 N

values which minutes part overflows the Sexagesimal system. Therefore it results in wrong coordinates.

**Comment by roman-dvorak** [comment]
Fixed - error was caused by missing initial 0 in coordinates with minutes bellow 10.

`[Latitude]049d748 N`
instend of
`[Latitude]049d0748 N`
